### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by abaghela** [UBC-MDS/DSCI522_group17#13]
Excellent proposal, I enjoyed reading it. Im confident this will lead to a wine company and you will make alot of money. However, something that should be addressed is the the output variable. How do you decide what is poor, intermediate, and good wine?

**Comment by hellosakshi** [comment]
Thanks @abaghela , we incorporated the proposed changes.

**Comment by hellosakshi** [comment]
Thanks @abaghela , we incorporated the proposed changes.
