### ISSUE TITLE
Milestone 2 General Feedback

### ISSUE THREAD

**Issue by ahofmann4** [UBC-MDS/DSCI522_group17#22]
Hi Group 17!

Well done on your project! And I had no problems running your code.

- previous comments from TA appear to have been addressed, would be useful to see a comment from a group member stating what commit fixed it, and or closing the issue. Use of issues to track progress overall would be good to see group's communication
- more specific commit messages would be useful 

I have some suggestions for your Report:

1) Table of contents missing, 
2) fig 1 - remove black graph panel, 
3) fig 1 and 2 have some redundance - could just remove fig 1 and only keep fig 2 in report (up to you)
4) Table 2 - only has one value - doesn't need to be in a table, can just be reported in the text
5) discussion could use some explanation on how they might address some of the issues like class imbalance

**Comment by jachang0628** [comment]
Thank you for the feedback! The suggestions have been addressed.
