### ISSUE TITLE
Peer Review from Hazel

### ISSUE THREAD

**Issue by HazelJJJ** [UBC-MDS/DSCI522_group17#24]
Hello Team 17,

I am Hazel and I am very happy to read your project! First I want to congratulate on your project! Well done! Below are some of my suggestions. 

Documentation: the project is properly documented. Everything is well managed and all the folders you created make sense.

Code: I have no problem running your make file but I get slightly different results compare to yours in the result. Perhaps to make your code/project more reproducible, you may want to consider set random state in your code.

Analysis and reasoning: The logic in your analysis and results is very clear and easy to follow.  l appreciated the explanation of how your get the new column `type of wine` and how you group your target into different groups. Those information are very helpful for me to better understand your report. One thing you may want to consider is to introduce more about the features in your data analysis. Maybe talk a little bit about what are some important features that you are taking into consideration, or is there any correlation between the features? I saw you did a great job in your EDA.ipynb file, perhaps you could put a link in your report to your EDA in case people want to know more about your data.

Communication: The report is clear and easy to follow. One change you may want to consider is to improve the readability of your plots a little bit. It will be more helpful to add title and rename some of the axis for the plot. For example, in your Fig2, Since all the y axis are Density, and all the legends ae quality level, you may want to simplify them by only keeping one legend and remove the name of y axis (Maybe rename some of your x axis as well) to improve readability.

Overall I think your group did an excellent job on this project. My suggestions above are just some minor change you could consider for improvement.

Once again! Congratulations and Well Done !!

**Comment by jachang0628** [comment]
Thank you for your feedback! We will look into your suggestions!
