### ISSUE TITLE
Peer review from Chuang

### ISSUE THREAD

**Issue by chuangw6** [UBC-MDS/DSCI522_group17#26]
Hi, Group 17
Great work! My feedback is as follows. Hope you find it helpful.

- The project documentation looks great to me. The summary part is well written and easy to understand what data you use and what ML models you have experimented with.
- The analysis is reasonable, but it would be great to document what is the motivation that you split the target into 3 categories. Is it because this can help others understand the classification problem etc?
- File naming could be improved. The current file names might be confusing for external stakeholders. For instance, it might be hard to interpret what the file `dt_cr.py` is doing at first glance.
- Project organization could be improved. For example, it would be more organized to have different source files in different subfolders under `src`. This will help others to understand what are the main components of this project.
- In terms of coding, most variables are named properly and functions are well-documented with docstrings. However, most of the functions in your scripts might be too long. One possible way to handle this is to delegate different functionalities into a couple of helper functions. This will not only help others understand your code but also help the team to debug and extend your analysis in future milestones. For instance, in the main function of `pre.py` script, the preparing data part and transform part could be separated into two helper functions and they can be called in the main function.

Please do let me know if you need further clarification or want to discuss more. Thank you!

**Comment by jachang0628** [comment]
Thank you for your feedback! We will look into your suggestions!
